// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celinium/interstaking/source_chain.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DelegationStrategy struct {
	Percentage       uint32 `protobuf:"varint,1,opt,name=percentage,proto3" json:"percentage,omitempty"`
	ValidatorAddress string `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
}

func (m *DelegationStrategy) Reset()         { *m = DelegationStrategy{} }
func (m *DelegationStrategy) String() string { return proto.CompactTextString(m) }
func (*DelegationStrategy) ProtoMessage()    {}
func (*DelegationStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe65ea8bc8bbff20, []int{0}
}
func (m *DelegationStrategy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegationStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegationStrategy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegationStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegationStrategy.Merge(m, src)
}
func (m *DelegationStrategy) XXX_Size() int {
	return m.Size()
}
func (m *DelegationStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegationStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_DelegationStrategy proto.InternalMessageInfo

func (m *DelegationStrategy) GetPercentage() uint32 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func (m *DelegationStrategy) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

type SourceChainMetadata struct {
	IbcClientId     string `protobuf:"bytes,1,opt,name=ibcClientId,proto3" json:"ibcClientId,omitempty"`
	IbcConnectionId string `protobuf:"bytes,2,opt,name=ibcConnectionId,proto3" json:"ibcConnectionId,omitempty"`
	// The inter chain account at control chain
	ICAControlAddr string `protobuf:"bytes,3,opt,name=ICAControlAddr,proto3" json:"ICAControlAddr,omitempty"`
	StakingDenom   string `protobuf:"bytes,4,opt,name=stakingDenom,proto3" json:"stakingDenom,omitempty"`
	// The strategy for assigning delegation
	DelegateStrategy []*DelegationStrategy `protobuf:"bytes,5,rep,name=delegate_strategy,json=delegateStrategy,proto3" json:"delegate_strategy,omitempty"`
}

func (m *SourceChainMetadata) Reset()         { *m = SourceChainMetadata{} }
func (m *SourceChainMetadata) String() string { return proto.CompactTextString(m) }
func (*SourceChainMetadata) ProtoMessage()    {}
func (*SourceChainMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe65ea8bc8bbff20, []int{1}
}
func (m *SourceChainMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SourceChainMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SourceChainMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SourceChainMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceChainMetadata.Merge(m, src)
}
func (m *SourceChainMetadata) XXX_Size() int {
	return m.Size()
}
func (m *SourceChainMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceChainMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_SourceChainMetadata proto.InternalMessageInfo

type SourceChainDelegation struct {
	Delegations []*ICADelegation `protobuf:"bytes,1,rep,name=delegations,proto3" json:"delegations,omitempty"`
}

func (m *SourceChainDelegation) Reset()         { *m = SourceChainDelegation{} }
func (m *SourceChainDelegation) String() string { return proto.CompactTextString(m) }
func (*SourceChainDelegation) ProtoMessage()    {}
func (*SourceChainDelegation) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe65ea8bc8bbff20, []int{2}
}
func (m *SourceChainDelegation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SourceChainDelegation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SourceChainDelegation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SourceChainDelegation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceChainDelegation.Merge(m, src)
}
func (m *SourceChainDelegation) XXX_Size() int {
	return m.Size()
}
func (m *SourceChainDelegation) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceChainDelegation.DiscardUnknown(m)
}

var xxx_messageInfo_SourceChainDelegation proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DelegationStrategy)(nil), "celinlim.interstaking.DelegationStrategy")
	proto.RegisterType((*SourceChainMetadata)(nil), "celinlim.interstaking.SourceChainMetadata")
	proto.RegisterType((*SourceChainDelegation)(nil), "celinlim.interstaking.SourceChainDelegation")
}

func init() {
	proto.RegisterFile("celinium/interstaking/source_chain.proto", fileDescriptor_fe65ea8bc8bbff20)
}

var fileDescriptor_fe65ea8bc8bbff20 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xed, 0x16, 0x10, 0xdd, 0xf0, 0xa7, 0x5d, 0x5a, 0xc9, 0xe4, 0xb0, 0x8d, 0xa2, 0x0a,
	0x99, 0x43, 0x63, 0x15, 0x2e, 0x88, 0x5b, 0xea, 0x82, 0x94, 0x03, 0x17, 0x47, 0xe2, 0xc0, 0x25,
	0x5a, 0xef, 0x8e, 0xcc, 0x0a, 0x7b, 0x37, 0xda, 0xdd, 0x56, 0x54, 0xbc, 0x00, 0x37, 0x78, 0x84,
	0x3e, 0x04, 0x0f, 0xc1, 0xb1, 0xe2, 0xc4, 0x11, 0x25, 0x17, 0x1e, 0x03, 0x79, 0xd7, 0x4e, 0x4c,
	0x09, 0x37, 0xcf, 0x6f, 0xbe, 0xf1, 0x37, 0xfa, 0x76, 0x50, 0xcc, 0xa0, 0x14, 0x52, 0x9c, 0x57,
	0x89, 0x90, 0x16, 0xb4, 0xb1, 0xf4, 0x83, 0x90, 0x45, 0x62, 0xd4, 0xb9, 0x66, 0x30, 0x63, 0xef,
	0xa9, 0x90, 0xa3, 0xb9, 0x56, 0x56, 0xe1, 0x03, 0xa7, 0x2c, 0x45, 0x35, 0xea, 0x2a, 0xfb, 0xfb,
	0x85, 0x2a, 0x94, 0x53, 0x24, 0xf5, 0x97, 0x17, 0xf7, 0x1f, 0x33, 0x65, 0x2a, 0x65, 0x66, 0xbe,
	0xe1, 0x8b, 0xa6, 0x45, 0x7c, 0x95, 0xe4, 0xd4, 0x40, 0x72, 0x71, 0x92, 0x83, 0xa5, 0x27, 0x09,
	0x53, 0xad, 0x4f, 0xff, 0x68, 0xf3, 0x46, 0x1c, 0x4a, 0x28, 0xa8, 0x05, 0xaf, 0x1a, 0x7e, 0x42,
	0xf8, 0xcc, 0x13, 0xa1, 0xe4, 0xd4, 0x6a, 0x6a, 0xa1, 0xb8, 0xc4, 0x04, 0xa1, 0x39, 0x68, 0x06,
	0xd2, 0xd2, 0x02, 0xa2, 0x70, 0x10, 0xc6, 0xf7, 0xb3, 0x0e, 0xc1, 0xaf, 0xd0, 0xde, 0x05, 0x2d,
	0x05, 0xa7, 0x56, 0xe9, 0x19, 0xe5, 0x5c, 0x83, 0x31, 0xd1, 0xd6, 0x20, 0x8c, 0x77, 0x4e, 0xa3,
	0x1f, 0xdf, 0x8e, 0xf7, 0x9b, 0x45, 0xc7, 0xbe, 0x33, 0xb5, 0x5a, 0xc8, 0x22, 0xdb, 0x5d, 0x8d,
	0x34, 0x7c, 0xf8, 0x65, 0x0b, 0x3d, 0x9a, 0xba, 0x84, 0xd2, 0x3a, 0xa0, 0x37, 0x60, 0x29, 0xa7,
	0x96, 0xe2, 0x01, 0xea, 0x89, 0x9c, 0xa5, 0xa5, 0x00, 0x69, 0x27, 0xdc, 0xf9, 0xef, 0x64, 0x5d,
	0x84, 0x63, 0xf4, 0xb0, 0x2e, 0x95, 0x94, 0xc0, 0xea, 0xcd, 0x27, 0xdc, 0xdb, 0x67, 0x37, 0x31,
	0x7e, 0x82, 0x1e, 0x4c, 0xd2, 0x71, 0xaa, 0xa4, 0xd5, 0xaa, 0xac, 0x8d, 0xa3, 0x6d, 0x27, 0xbc,
	0x41, 0xf1, 0x10, 0xdd, 0x6b, 0x22, 0x3a, 0x03, 0xa9, 0xaa, 0xe8, 0x96, 0x53, 0xfd, 0xc5, 0xf0,
	0x5b, 0xb4, 0xd7, 0xc6, 0x37, 0x33, 0x4d, 0x56, 0xd1, 0xed, 0xc1, 0x76, 0xdc, 0x7b, 0xf6, 0x74,
	0xb4, 0xf1, 0x59, 0x47, 0xff, 0x86, 0x9b, 0xed, 0xb6, 0xff, 0x68, 0xc9, 0xcb, 0xbb, 0x9f, 0xaf,
	0x0e, 0x83, 0xdf, 0x57, 0x87, 0xc1, 0x50, 0xa0, 0x83, 0x4e, 0x20, 0xeb, 0x61, 0xfc, 0x1a, 0xf5,
	0xf8, 0xaa, 0x32, 0x51, 0xe8, 0x4c, 0x8f, 0xfe, 0x63, 0x3a, 0x49, 0xc7, 0xeb, 0xd1, 0xac, 0x3b,
	0xb8, 0xb6, 0x3a, 0x7d, 0xf1, 0x7d, 0x41, 0xc2, 0xeb, 0x05, 0x09, 0x7f, 0x2d, 0x48, 0xf8, 0x75,
	0x49, 0x82, 0xeb, 0x25, 0x09, 0x7e, 0x2e, 0x49, 0xf0, 0x8e, 0xac, 0x2e, 0xe7, 0xa3, 0xbf, 0x9d,
	0xe3, 0xf6, 0x78, 0xec, 0xe5, 0x1c, 0x4c, 0x7e, 0xc7, 0x9d, 0xce, 0xf3, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xf4, 0x75, 0x2b, 0xa9, 0xf4, 0x02, 0x00, 0x00,
}

func (m *DelegationStrategy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegationStrategy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegationStrategy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Percentage != 0 {
		i = encodeVarintSourceChain(dAtA, i, uint64(m.Percentage))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SourceChainMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SourceChainMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SourceChainMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DelegateStrategy) > 0 {
		for iNdEx := len(m.DelegateStrategy) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DelegateStrategy[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSourceChain(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.StakingDenom) > 0 {
		i -= len(m.StakingDenom)
		copy(dAtA[i:], m.StakingDenom)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.StakingDenom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ICAControlAddr) > 0 {
		i -= len(m.ICAControlAddr)
		copy(dAtA[i:], m.ICAControlAddr)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.ICAControlAddr)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.IbcConnectionId) > 0 {
		i -= len(m.IbcConnectionId)
		copy(dAtA[i:], m.IbcConnectionId)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.IbcConnectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.IbcClientId) > 0 {
		i -= len(m.IbcClientId)
		copy(dAtA[i:], m.IbcClientId)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.IbcClientId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SourceChainDelegation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SourceChainDelegation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SourceChainDelegation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Delegations) > 0 {
		for iNdEx := len(m.Delegations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Delegations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSourceChain(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintSourceChain(dAtA []byte, offset int, v uint64) int {
	offset -= sovSourceChain(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DelegationStrategy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Percentage != 0 {
		n += 1 + sovSourceChain(uint64(m.Percentage))
	}
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	return n
}

func (m *SourceChainMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IbcClientId)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	l = len(m.IbcConnectionId)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	l = len(m.ICAControlAddr)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	l = len(m.StakingDenom)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	if len(m.DelegateStrategy) > 0 {
		for _, e := range m.DelegateStrategy {
			l = e.Size()
			n += 1 + l + sovSourceChain(uint64(l))
		}
	}
	return n
}

func (m *SourceChainDelegation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Delegations) > 0 {
		for _, e := range m.Delegations {
			l = e.Size()
			n += 1 + l + sovSourceChain(uint64(l))
		}
	}
	return n
}

func sovSourceChain(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSourceChain(x uint64) (n int) {
	return sovSourceChain(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DelegationStrategy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSourceChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegationStrategy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegationStrategy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Percentage", wireType)
			}
			m.Percentage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Percentage |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSourceChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSourceChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SourceChainMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSourceChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SourceChainMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SourceChainMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ICAControlAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ICAControlAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegateStrategy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegateStrategy = append(m.DelegateStrategy, &DelegationStrategy{})
			if err := m.DelegateStrategy[len(m.DelegateStrategy)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSourceChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSourceChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SourceChainDelegation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSourceChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SourceChainDelegation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SourceChainDelegation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegations = append(m.Delegations, &ICADelegation{})
			if err := m.Delegations[len(m.Delegations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSourceChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSourceChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSourceChain(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSourceChain
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSourceChain
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSourceChain
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSourceChain
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSourceChain        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSourceChain          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSourceChain = fmt.Errorf("proto: unexpected end of group")
)
