// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celinium/liquidstake/v1/source_chain.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Validator struct {
	// The address of source chain validator account.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Total allocated amount.
	TokenAmount Int `protobuf:"bytes,2,opt,name=tokenAmount,proto3,customtype=Int" json:"tokenAmount"`
	// The weight used for distribute delegation funds.
	Weight uint64 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_9717b2e9147633e9, []int{0}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return m.Size()
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Validator) GetWeight() uint64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type SourceChain struct {
	// The chain id of source chain.
	ChainID string `protobuf:"bytes,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	// ibc connection id
	ConnectionID string `protobuf:"bytes,2,opt,name=connectionID,proto3" json:"connectionID,omitempty"`
	// ibc transfer channel id
	TransferChannelID string `protobuf:"bytes,3,opt,name=transferChannelID,proto3" json:"transferChannelID,omitempty"`
	// validator address prefix of source chain.
	Bech32ValidatorAddrPrefix string      `protobuf:"bytes,4,opt,name=bech32ValidatorAddrPrefix,proto3" json:"bech32ValidatorAddrPrefix,omitempty"`
	Validators                []Validator `protobuf:"bytes,5,rep,name=validators,proto3" json:"validators"`
	// The address of interchain account for withdraw POS reward
	WithdrawAddress string `protobuf:"bytes,6,opt,name=withdrawAddress,proto3" json:"withdrawAddress,omitempty"`
	// The address of for ecsrow user's token
	EcsrowAddress string `protobuf:"bytes,7,opt,name=ecsrowAddress,proto3" json:"ecsrowAddress,omitempty"`
	// The address of interchain account for delegation
	DelegateAddress string `protobuf:"bytes,8,opt,name=delegateAddress,proto3" json:"delegateAddress,omitempty"`
	// Redemption ratio in the current epoch
	Redemptionratio Dec `protobuf:"bytes,9,opt,name=redemptionratio,proto3,customtype=Dec" json:"redemptionratio"`
	// The denom of cross chain token.
	IbcDenom string `protobuf:"bytes,10,opt,name=ibcDenom,proto3" json:"ibcDenom,omitempty"`
	// The denom of source chain native token.
	NativeDenom string `protobuf:"bytes,11,opt,name=nativeDenom,proto3" json:"nativeDenom,omitempty"`
	// Derivative token denom generated after liquid stake
	DerivativeDenom string `protobuf:"bytes,12,opt,name=derivativeDenom,proto3" json:"derivativeDenom,omitempty"`
	// The amount of staked token.
	StakedAmount Int `protobuf:"bytes,13,opt,name=stakedAmount,proto3,customtype=Int" json:"stakedAmount"`
}

func (m *SourceChain) Reset()         { *m = SourceChain{} }
func (m *SourceChain) String() string { return proto.CompactTextString(m) }
func (*SourceChain) ProtoMessage()    {}
func (*SourceChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_9717b2e9147633e9, []int{1}
}
func (m *SourceChain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SourceChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SourceChain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SourceChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceChain.Merge(m, src)
}
func (m *SourceChain) XXX_Size() int {
	return m.Size()
}
func (m *SourceChain) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceChain.DiscardUnknown(m)
}

var xxx_messageInfo_SourceChain proto.InternalMessageInfo

func (m *SourceChain) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *SourceChain) GetConnectionID() string {
	if m != nil {
		return m.ConnectionID
	}
	return ""
}

func (m *SourceChain) GetTransferChannelID() string {
	if m != nil {
		return m.TransferChannelID
	}
	return ""
}

func (m *SourceChain) GetBech32ValidatorAddrPrefix() string {
	if m != nil {
		return m.Bech32ValidatorAddrPrefix
	}
	return ""
}

func (m *SourceChain) GetValidators() []Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *SourceChain) GetWithdrawAddress() string {
	if m != nil {
		return m.WithdrawAddress
	}
	return ""
}

func (m *SourceChain) GetEcsrowAddress() string {
	if m != nil {
		return m.EcsrowAddress
	}
	return ""
}

func (m *SourceChain) GetDelegateAddress() string {
	if m != nil {
		return m.DelegateAddress
	}
	return ""
}

func (m *SourceChain) GetIbcDenom() string {
	if m != nil {
		return m.IbcDenom
	}
	return ""
}

func (m *SourceChain) GetNativeDenom() string {
	if m != nil {
		return m.NativeDenom
	}
	return ""
}

func (m *SourceChain) GetDerivativeDenom() string {
	if m != nil {
		return m.DerivativeDenom
	}
	return ""
}

type Validators struct {
	Validators []Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators"`
}

func (m *Validators) Reset()         { *m = Validators{} }
func (m *Validators) String() string { return proto.CompactTextString(m) }
func (*Validators) ProtoMessage()    {}
func (*Validators) Descriptor() ([]byte, []int) {
	return fileDescriptor_9717b2e9147633e9, []int{2}
}
func (m *Validators) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Validators) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Validators.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Validators) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validators.Merge(m, src)
}
func (m *Validators) XXX_Size() int {
	return m.Size()
}
func (m *Validators) XXX_DiscardUnknown() {
	xxx_messageInfo_Validators.DiscardUnknown(m)
}

var xxx_messageInfo_Validators proto.InternalMessageInfo

func (m *Validators) GetValidators() []Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func init() {
	proto.RegisterType((*Validator)(nil), "celinium.liquidstake.v1.Validator")
	proto.RegisterType((*SourceChain)(nil), "celinium.liquidstake.v1.SourceChain")
	proto.RegisterType((*Validators)(nil), "celinium.liquidstake.v1.Validators")
}

func init() {
	proto.RegisterFile("celinium/liquidstake/v1/source_chain.proto", fileDescriptor_9717b2e9147633e9)
}

var fileDescriptor_9717b2e9147633e9 = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xbd, 0x6e, 0x1a, 0x41,
	0x10, 0xe6, 0x62, 0x0c, 0x66, 0xc0, 0xb2, 0xb2, 0xb2, 0x92, 0x03, 0x45, 0x07, 0xa2, 0x42, 0x51,
	0x0c, 0x32, 0x96, 0x52, 0xe4, 0x4f, 0x32, 0x50, 0x84, 0x2e, 0x3a, 0x4b, 0x14, 0x69, 0xac, 0x65,
	0x6f, 0x0c, 0x2b, 0xc3, 0x2e, 0xd9, 0x5b, 0xc0, 0x79, 0x8b, 0xd4, 0xa9, 0xf2, 0x10, 0xce, 0x3b,
	0xb8, 0xb4, 0x5c, 0x45, 0x29, 0xac, 0x08, 0x9a, 0x3c, 0x46, 0x74, 0x7b, 0x70, 0xb9, 0x23, 0xb2,
	0x90, 0xd2, 0x31, 0xf3, 0x7d, 0xdf, 0x30, 0x33, 0xdf, 0xdc, 0xc2, 0x73, 0x86, 0x23, 0x2e, 0xf8,
	0x74, 0xdc, 0x18, 0xf1, 0x4f, 0x53, 0xee, 0xf9, 0x9a, 0x5e, 0x62, 0x63, 0x76, 0xdc, 0xf0, 0xe5,
	0x54, 0x31, 0x3c, 0x67, 0x43, 0xca, 0x45, 0x7d, 0xa2, 0xa4, 0x96, 0xe4, 0xe9, 0x9a, 0x5b, 0x8f,
	0x71, 0xeb, 0xb3, 0xe3, 0xd2, 0xe1, 0x40, 0x0e, 0xa4, 0xe1, 0x34, 0x82, 0x5f, 0x21, 0xbd, 0x54,
	0x64, 0xd2, 0x1f, 0x4b, 0xff, 0x3c, 0x04, 0xc2, 0x20, 0x84, 0xaa, 0x5f, 0x2d, 0xc8, 0xf5, 0xe8,
	0x88, 0x7b, 0x54, 0x4b, 0x45, 0x9a, 0x90, 0xa5, 0x9e, 0xa7, 0xd0, 0xf7, 0x6d, 0xab, 0x62, 0xd5,
	0x72, 0x2d, 0xfb, 0xee, 0xfa, 0xe8, 0x70, 0x25, 0x38, 0x0d, 0x91, 0x33, 0xad, 0xb8, 0x18, 0xb8,
	0x6b, 0x22, 0x79, 0x0d, 0x79, 0x2d, 0x2f, 0x51, 0x9c, 0x8e, 0xe5, 0x54, 0x68, 0xfb, 0x91, 0xd1,
	0x15, 0x6f, 0xee, 0xcb, 0xa9, 0x9f, 0xf7, 0xe5, 0x9d, 0xae, 0xd0, 0x77, 0xd7, 0x47, 0xb0, 0x2a,
	0xd1, 0x15, 0xda, 0x8d, 0xb3, 0xc9, 0x13, 0xc8, 0xcc, 0x91, 0x0f, 0x86, 0xda, 0xde, 0xa9, 0x58,
	0xb5, 0xb4, 0xbb, 0x8a, 0x5e, 0xa5, 0x7f, 0x7f, 0x2b, 0x5b, 0xd5, 0xef, 0xbb, 0x90, 0x3f, 0x33,
	0xd3, 0xb7, 0x83, 0xe1, 0x89, 0x0d, 0x59, 0xb3, 0x85, 0x6e, 0x27, 0x6c, 0xcf, 0x5d, 0x87, 0xa4,
	0x0a, 0x05, 0x26, 0x85, 0x40, 0xa6, 0xb9, 0x0c, 0x60, 0xd3, 0x85, 0x9b, 0xc8, 0x91, 0x17, 0xf0,
	0x58, 0x2b, 0x2a, 0xfc, 0x0b, 0x54, 0xed, 0x21, 0x15, 0x02, 0x47, 0xdd, 0x8e, 0xf9, 0xdb, 0x9c,
	0xfb, 0x2f, 0x40, 0xde, 0x40, 0xb1, 0x8f, 0x6c, 0x78, 0xd2, 0x8c, 0xb6, 0x13, 0xcc, 0xff, 0x41,
	0xe1, 0x05, 0xbf, 0xb2, 0xd3, 0x46, 0xf5, 0x30, 0x81, 0xbc, 0x07, 0x98, 0xad, 0xd3, 0xbe, 0xbd,
	0x5b, 0xd9, 0xa9, 0xe5, 0x9b, 0xd5, 0xfa, 0x03, 0xae, 0xd5, 0xa3, 0x0a, 0xad, 0x74, 0xb0, 0x37,
	0x37, 0xa6, 0x25, 0x2d, 0x38, 0x98, 0x73, 0x3d, 0xf4, 0x14, 0x9d, 0xaf, 0x0c, 0xb0, 0x33, 0x5b,
	0xac, 0xd9, 0x14, 0x90, 0x77, 0xb0, 0x8f, 0xcc, 0x57, 0x32, 0xaa, 0x90, 0xdd, 0x52, 0x21, 0x49,
	0x0f, 0x7a, 0xf0, 0x70, 0x84, 0x03, 0xaa, 0x71, 0x5d, 0x61, 0x6f, 0x5b, 0x0f, 0x1b, 0x02, 0xd2,
	0x86, 0x03, 0x85, 0x1e, 0x8e, 0x27, 0x81, 0x1b, 0x8a, 0x6a, 0x2e, 0xed, 0x5c, 0xf2, 0x54, 0x3a,
	0xc8, 0x62, 0xa7, 0xd2, 0x41, 0xe6, 0x6e, 0x2a, 0x48, 0x09, 0xf6, 0x78, 0x9f, 0x75, 0x50, 0xc8,
	0xb1, 0x0d, 0xc6, 0x83, 0x28, 0x26, 0x15, 0xc8, 0x0b, 0xaa, 0xf9, 0x0c, 0x43, 0x38, 0x6f, 0xe0,
	0x78, 0x8a, 0xd4, 0x82, 0x31, 0x14, 0x9f, 0xc5, 0x58, 0x05, 0xc3, 0xda, 0x4c, 0x93, 0xb7, 0x50,
	0x30, 0xe6, 0x78, 0xab, 0xa3, 0xde, 0xdf, 0x76, 0xd4, 0x09, 0x7a, 0xb5, 0x07, 0xd0, 0xfb, 0xeb,
	0x60, 0xf2, 0x16, 0xac, 0xff, 0xbf, 0x85, 0xd6, 0xcb, 0x9b, 0x85, 0x63, 0xdd, 0x2e, 0x1c, 0xeb,
	0xd7, 0xc2, 0xb1, 0xbe, 0x2c, 0x9d, 0xd4, 0xed, 0xd2, 0x49, 0xfd, 0x58, 0x3a, 0xa9, 0x8f, 0xcf,
	0xa2, 0xc7, 0xe3, 0x2a, 0xf1, 0x7c, 0xe8, 0xcf, 0x13, 0xf4, 0xfb, 0x19, 0xf3, 0xad, 0x9f, 0xfc,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x13, 0xf3, 0xd6, 0x4f, 0x63, 0x04, 0x00, 0x00,
}

func (this *Validator) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Validator)
	if !ok {
		that2, ok := that.(Validator)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Address != that1.Address {
		return false
	}
	if !this.TokenAmount.Equal(that1.TokenAmount) {
		return false
	}
	if this.Weight != that1.Weight {
		return false
	}
	return true
}
func (m *Validator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Validator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Validator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Weight != 0 {
		i = encodeVarintSourceChain(dAtA, i, uint64(m.Weight))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.TokenAmount.Size()
		i -= size
		if _, err := m.TokenAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSourceChain(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SourceChain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SourceChain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SourceChain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.StakedAmount.Size()
		i -= size
		if _, err := m.StakedAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSourceChain(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	if len(m.DerivativeDenom) > 0 {
		i -= len(m.DerivativeDenom)
		copy(dAtA[i:], m.DerivativeDenom)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.DerivativeDenom)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.NativeDenom) > 0 {
		i -= len(m.NativeDenom)
		copy(dAtA[i:], m.NativeDenom)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.NativeDenom)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.IbcDenom) > 0 {
		i -= len(m.IbcDenom)
		copy(dAtA[i:], m.IbcDenom)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.IbcDenom)))
		i--
		dAtA[i] = 0x52
	}
	{
		size := m.Redemptionratio.Size()
		i -= size
		if _, err := m.Redemptionratio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSourceChain(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if len(m.DelegateAddress) > 0 {
		i -= len(m.DelegateAddress)
		copy(dAtA[i:], m.DelegateAddress)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.DelegateAddress)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.EcsrowAddress) > 0 {
		i -= len(m.EcsrowAddress)
		copy(dAtA[i:], m.EcsrowAddress)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.EcsrowAddress)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.WithdrawAddress) > 0 {
		i -= len(m.WithdrawAddress)
		copy(dAtA[i:], m.WithdrawAddress)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.WithdrawAddress)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Validators) > 0 {
		for iNdEx := len(m.Validators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Validators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSourceChain(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Bech32ValidatorAddrPrefix) > 0 {
		i -= len(m.Bech32ValidatorAddrPrefix)
		copy(dAtA[i:], m.Bech32ValidatorAddrPrefix)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.Bech32ValidatorAddrPrefix)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TransferChannelID) > 0 {
		i -= len(m.TransferChannelID)
		copy(dAtA[i:], m.TransferChannelID)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.TransferChannelID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConnectionID) > 0 {
		i -= len(m.ConnectionID)
		copy(dAtA[i:], m.ConnectionID)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.ConnectionID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintSourceChain(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Validators) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Validators) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Validators) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Validators) > 0 {
		for iNdEx := len(m.Validators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Validators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSourceChain(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintSourceChain(dAtA []byte, offset int, v uint64) int {
	offset -= sovSourceChain(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Validator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	l = m.TokenAmount.Size()
	n += 1 + l + sovSourceChain(uint64(l))
	if m.Weight != 0 {
		n += 1 + sovSourceChain(uint64(m.Weight))
	}
	return n
}

func (m *SourceChain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	l = len(m.ConnectionID)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	l = len(m.TransferChannelID)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	l = len(m.Bech32ValidatorAddrPrefix)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	if len(m.Validators) > 0 {
		for _, e := range m.Validators {
			l = e.Size()
			n += 1 + l + sovSourceChain(uint64(l))
		}
	}
	l = len(m.WithdrawAddress)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	l = len(m.EcsrowAddress)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	l = len(m.DelegateAddress)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	l = m.Redemptionratio.Size()
	n += 1 + l + sovSourceChain(uint64(l))
	l = len(m.IbcDenom)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	l = len(m.NativeDenom)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	l = len(m.DerivativeDenom)
	if l > 0 {
		n += 1 + l + sovSourceChain(uint64(l))
	}
	l = m.StakedAmount.Size()
	n += 1 + l + sovSourceChain(uint64(l))
	return n
}

func (m *Validators) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Validators) > 0 {
		for _, e := range m.Validators {
			l = e.Size()
			n += 1 + l + sovSourceChain(uint64(l))
		}
	}
	return n
}

func sovSourceChain(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSourceChain(x uint64) (n int) {
	return sovSourceChain(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Validator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSourceChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Validator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Validator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TokenAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			m.Weight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Weight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSourceChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSourceChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SourceChain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSourceChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SourceChain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SourceChain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferChannelID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransferChannelID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bech32ValidatorAddrPrefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bech32ValidatorAddrPrefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validators = append(m.Validators, Validator{})
			if err := m.Validators[len(m.Validators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EcsrowAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EcsrowAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegateAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegateAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Redemptionratio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Redemptionratio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NativeDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NativeDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DerivativeDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DerivativeDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakedAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StakedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSourceChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSourceChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Validators) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSourceChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Validators: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Validators: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSourceChain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSourceChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validators = append(m.Validators, Validator{})
			if err := m.Validators[len(m.Validators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSourceChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSourceChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSourceChain(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSourceChain
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSourceChain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSourceChain
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSourceChain
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSourceChain
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSourceChain        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSourceChain          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSourceChain = fmt.Errorf("proto: unexpected end of group")
)
