// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celinium/liquidstake/v1/stake.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// The record of source chain delegation in a epoch.
type DelegationRecord struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Users delegated tokens accumulated by the specified epoch
	DelegationCoin types.Coin `protobuf:"bytes,2,opt,name=delegationCoin,proto3" json:"delegationCoin"`
	// Status of the record.
	// A DelegationRecord goes through the following status:
	//   1) Pending: The epoch he is in is not over yet
	//   2) Transfering: Transferring user-delegated funds back to the source chain.
	//   3) Transferred: Transfer back to source chain successfully.Because the funds
	//      need to be delegated on the source chain immediately, this state will not be saved.
	//   4) Delegating: Cross-chain delegation is being executed through IBC
	//   5) Done: Cross-chain delegation has be done. If this state is reached, then this
	//      record will be deleted, so this state will not be recorded."
	// Above is a successful state, but there are also states that represent failure.
	//   1）TransferFailed: An error occurred during the process of transferring funds back to the source chain.
	//   2) DelegateFailed: An error occurred during the process of delegating in source chain.
	Status DelegationRecordStatus `protobuf:"varint,3,opt,name=status,proto3,customtype=DelegationRecordStatus" json:"status"`
	// The number of created epoch
	EpochNumber uint64 `protobuf:"varint,4,opt,name=epochNumber,proto3" json:"epochNumber,omitempty"`
	ChainID     string `protobuf:"bytes,5,opt,name=chainID,proto3" json:"chainID,omitempty"`
	// A portion of the `DelegationCoin` that have been transferred to the source chain.
	// This usually happens when reinvesting to get back the source chain staking rewards,
	TransferredAmount Int `protobuf:"bytes,6,opt,name=transferredAmount,proto3,customtype=Int" json:"transferredAmount"`
}

func (m *DelegationRecord) Reset()         { *m = DelegationRecord{} }
func (m *DelegationRecord) String() string { return proto.CompactTextString(m) }
func (*DelegationRecord) ProtoMessage()    {}
func (*DelegationRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_9beff2e65f7b246b, []int{0}
}
func (m *DelegationRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegationRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegationRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegationRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegationRecord.Merge(m, src)
}
func (m *DelegationRecord) XXX_Size() int {
	return m.Size()
}
func (m *DelegationRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegationRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DelegationRecord proto.InternalMessageInfo

func (m *DelegationRecord) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DelegationRecord) GetDelegationCoin() types.Coin {
	if m != nil {
		return m.DelegationCoin
	}
	return types.Coin{}
}

func (m *DelegationRecord) GetEpochNumber() uint64 {
	if m != nil {
		return m.EpochNumber
	}
	return 0
}

func (m *DelegationRecord) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

// UndelegationRecord represents a record of a delegator's undelegation action.
type UndelegationRecord struct {
	// Unique identifier for the undelegation record
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// The chain ID of the source chain where the undelegation was initiated.
	ChainID string `protobuf:"bytes,2,opt,name=chainID,proto3" json:"chainID,omitempty"`
	// The epoch of the undelegation, used to record the time or timestamp of the undelegation
	Epoch uint64 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// The delegator who canceled the delegation, i.e. the user who originally delegated
	Delegator string `protobuf:"bytes,4,opt,name=delegator,proto3" json:"delegator,omitempty"`
	// The recipient account for the redeemed funds.
	Receiver string `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// The amount and type of funds to be redeemed.
	RedeemToken types.Coin `protobuf:"bytes,6,opt,name=redeemToken,proto3" json:"redeemToken"`
	// The redemption status of the undelegation.
	// 1) Pending: The undelegation request has been submitted but not yet processed or completed.
	// 2) Claimable: The undelegation has been processed and the funds are available to be claimed by the delegator.
	// 3) Complete: The funds have been successfully claimed by the delegator.
	CliamStatus UndelegationRecordStatus `protobuf:"varint,7,opt,name=cliamStatus,proto3,customtype=UndelegationRecordStatus" json:"cliamStatus"`
}

func (m *UndelegationRecord) Reset()         { *m = UndelegationRecord{} }
func (m *UndelegationRecord) String() string { return proto.CompactTextString(m) }
func (*UndelegationRecord) ProtoMessage()    {}
func (*UndelegationRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_9beff2e65f7b246b, []int{1}
}
func (m *UndelegationRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UndelegationRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UndelegationRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UndelegationRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UndelegationRecord.Merge(m, src)
}
func (m *UndelegationRecord) XXX_Size() int {
	return m.Size()
}
func (m *UndelegationRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_UndelegationRecord.DiscardUnknown(m)
}

var xxx_messageInfo_UndelegationRecord proto.InternalMessageInfo

func (m *UndelegationRecord) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UndelegationRecord) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *UndelegationRecord) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *UndelegationRecord) GetDelegator() string {
	if m != nil {
		return m.Delegator
	}
	return ""
}

func (m *UndelegationRecord) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *UndelegationRecord) GetRedeemToken() types.Coin {
	if m != nil {
		return m.RedeemToken
	}
	return types.Coin{}
}

// Represents a record of an unbonding transaction, which captures the derivative token that was burned
// and the native token that is to be redeemed.
type Unbonding struct {
	ChainID                string `protobuf:"bytes,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	BurnedDerivativeAmount Int    `protobuf:"bytes,2,opt,name=burnedDerivativeAmount,proto3,customtype=Int" json:"burnedDerivativeAmount"`
	// The native tokens to be redeemed.
	RedeemNativeToken types.Coin `protobuf:"bytes,3,opt,name=redeemNativeToken,proto3" json:"redeemNativeToken"`
	// The time at which the unbonding will complete and the native tokens will be redeemable.
	UnbondTIme uint64 `protobuf:"varint,4,opt,name=unbondTIme,proto3" json:"unbondTIme,omitempty"`
	// The status of the unbonding.
	// 1) Pending: waiting for the current epoch to end
	// 2) Start: initiated the Unbonding process on the source chain
	// 3) Unbonding: successfully initiated the Unbonding process
	// 4) Transfering: Unbonding period has elapsed, redeeming funds from the source chain
	// 5) Done: funds have been successfully redeemed
	Status UnbondingStatus `protobuf:"varint,5,opt,name=status,proto3,customtype=UnbondingStatus" json:"status"`
	// The IDs of the UserUnbondRecord entries that correspond to this unbonding entry.
	UserUnbondRecordIds []string `protobuf:"bytes,6,rep,name=userUnbondRecordIds,proto3" json:"userUnbondRecordIds,omitempty"`
}

func (m *Unbonding) Reset()         { *m = Unbonding{} }
func (m *Unbonding) String() string { return proto.CompactTextString(m) }
func (*Unbonding) ProtoMessage()    {}
func (*Unbonding) Descriptor() ([]byte, []int) {
	return fileDescriptor_9beff2e65f7b246b, []int{2}
}
func (m *Unbonding) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Unbonding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Unbonding.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Unbonding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unbonding.Merge(m, src)
}
func (m *Unbonding) XXX_Size() int {
	return m.Size()
}
func (m *Unbonding) XXX_DiscardUnknown() {
	xxx_messageInfo_Unbonding.DiscardUnknown(m)
}

var xxx_messageInfo_Unbonding proto.InternalMessageInfo

func (m *Unbonding) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *Unbonding) GetRedeemNativeToken() types.Coin {
	if m != nil {
		return m.RedeemNativeToken
	}
	return types.Coin{}
}

func (m *Unbonding) GetUnbondTIme() uint64 {
	if m != nil {
		return m.UnbondTIme
	}
	return 0
}

func (m *Unbonding) GetUserUnbondRecordIds() []string {
	if m != nil {
		return m.UserUnbondRecordIds
	}
	return nil
}

// Represents a collection of unbonding entries for a given epoch.
type EpochUnbondings struct {
	// The epoch number.
	Epoch uint64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// The unbonding entries.
	Unbondings []Unbonding `protobuf:"bytes,2,rep,name=unbondings,proto3" json:"unbondings"`
}

func (m *EpochUnbondings) Reset()         { *m = EpochUnbondings{} }
func (m *EpochUnbondings) String() string { return proto.CompactTextString(m) }
func (*EpochUnbondings) ProtoMessage()    {}
func (*EpochUnbondings) Descriptor() ([]byte, []int) {
	return fileDescriptor_9beff2e65f7b246b, []int{3}
}
func (m *EpochUnbondings) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochUnbondings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochUnbondings.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochUnbondings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochUnbondings.Merge(m, src)
}
func (m *EpochUnbondings) XXX_Size() int {
	return m.Size()
}
func (m *EpochUnbondings) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochUnbondings.DiscardUnknown(m)
}

var xxx_messageInfo_EpochUnbondings proto.InternalMessageInfo

func (m *EpochUnbondings) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *EpochUnbondings) GetUnbondings() []Unbonding {
	if m != nil {
		return m.Unbondings
	}
	return nil
}

type IBCQuery struct {
	QueryType    string `protobuf:"bytes,1,opt,name=queryType,proto3" json:"queryType,omitempty"`
	QueryPathKey string `protobuf:"bytes,2,opt,name=queryPathKey,proto3" json:"queryPathKey,omitempty"`
	Timeout      uint64 `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	ChainID      string `protobuf:"bytes,4,opt,name=chainID,proto3" json:"chainID,omitempty"`
	ConnectionID string `protobuf:"bytes,5,opt,name=connectionID,proto3" json:"connectionID,omitempty"`
	Epoch        uint64 `protobuf:"varint,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *IBCQuery) Reset()         { *m = IBCQuery{} }
func (m *IBCQuery) String() string { return proto.CompactTextString(m) }
func (*IBCQuery) ProtoMessage()    {}
func (*IBCQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_9beff2e65f7b246b, []int{4}
}
func (m *IBCQuery) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IBCQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IBCQuery.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IBCQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IBCQuery.Merge(m, src)
}
func (m *IBCQuery) XXX_Size() int {
	return m.Size()
}
func (m *IBCQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_IBCQuery.DiscardUnknown(m)
}

var xxx_messageInfo_IBCQuery proto.InternalMessageInfo

func (m *IBCQuery) GetQueryType() string {
	if m != nil {
		return m.QueryType
	}
	return ""
}

func (m *IBCQuery) GetQueryPathKey() string {
	if m != nil {
		return m.QueryPathKey
	}
	return ""
}

func (m *IBCQuery) GetTimeout() uint64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *IBCQuery) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *IBCQuery) GetConnectionID() string {
	if m != nil {
		return m.ConnectionID
	}
	return ""
}

func (m *IBCQuery) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func init() {
	proto.RegisterType((*DelegationRecord)(nil), "celinium.liquidstake.v1.DelegationRecord")
	proto.RegisterType((*UndelegationRecord)(nil), "celinium.liquidstake.v1.UndelegationRecord")
	proto.RegisterType((*Unbonding)(nil), "celinium.liquidstake.v1.Unbonding")
	proto.RegisterType((*EpochUnbondings)(nil), "celinium.liquidstake.v1.EpochUnbondings")
	proto.RegisterType((*IBCQuery)(nil), "celinium.liquidstake.v1.IBCQuery")
}

func init() {
	proto.RegisterFile("celinium/liquidstake/v1/stake.proto", fileDescriptor_9beff2e65f7b246b)
}

var fileDescriptor_9beff2e65f7b246b = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xc1, 0x4e, 0xdb, 0x4c,
	0x10, 0x8e, 0x9d, 0x10, 0xc8, 0x86, 0x1f, 0x7e, 0xb6, 0x08, 0x0c, 0x42, 0xc6, 0x72, 0x2f, 0xb9,
	0xd4, 0x2e, 0x54, 0xe2, 0x4e, 0x48, 0x45, 0xad, 0xaa, 0xa8, 0xb8, 0x70, 0xe9, 0xa5, 0x72, 0xec,
	0x69, 0x58, 0x11, 0xef, 0x86, 0xf5, 0x3a, 0x6a, 0xde, 0xa2, 0x97, 0xbe, 0x43, 0x1f, 0xa0, 0xa7,
	0x3e, 0x01, 0xea, 0x09, 0xf5, 0x54, 0xf5, 0x80, 0x2a, 0x78, 0x91, 0xca, 0xeb, 0x8d, 0xe3, 0x10,
	0x50, 0xb9, 0x79, 0x66, 0xbf, 0x99, 0x9d, 0xef, 0x9b, 0xcf, 0x8b, 0x9e, 0x86, 0xd0, 0x27, 0x94,
	0xa4, 0xb1, 0xdb, 0x27, 0x17, 0x29, 0x89, 0x12, 0x11, 0x9c, 0x83, 0x3b, 0xdc, 0x71, 0xe5, 0x87,
	0x33, 0xe0, 0x4c, 0x30, 0xbc, 0x3e, 0x06, 0x39, 0x25, 0x90, 0x33, 0xdc, 0xd9, 0x5c, 0xed, 0xb1,
	0x1e, 0x93, 0x18, 0x37, 0xfb, 0xca, 0xe1, 0x9b, 0x1b, 0x21, 0x4b, 0x62, 0x96, 0x7c, 0xc8, 0x0f,
	0xf2, 0x40, 0x1d, 0x99, 0x79, 0xe4, 0x76, 0x83, 0x24, 0xbb, 0xa5, 0x0b, 0x22, 0xd8, 0x71, 0x43,
	0x46, 0x68, 0x7e, 0x6e, 0x7f, 0xd5, 0xd1, 0xff, 0x1d, 0xe8, 0x43, 0x2f, 0x10, 0x84, 0x51, 0x1f,
	0x42, 0xc6, 0x23, 0xbc, 0x84, 0x74, 0x12, 0x19, 0x9a, 0xa5, 0xb5, 0x6a, 0xbe, 0x4e, 0x22, 0x7c,
	0x88, 0x96, 0xa2, 0x02, 0x73, 0xc0, 0x08, 0x35, 0x74, 0x4b, 0x6b, 0x35, 0x77, 0x37, 0x1c, 0x75,
	0x57, 0xd6, 0xdd, 0x51, 0xdd, 0x9d, 0x0c, 0xd0, 0xae, 0x5d, 0x5e, 0x6f, 0x57, 0xfc, 0x3b, 0x65,
	0x78, 0x0f, 0xd5, 0x13, 0x11, 0x88, 0x34, 0x31, 0xaa, 0x96, 0xd6, 0xfa, 0xaf, 0x6d, 0x66, 0xa8,
	0xdf, 0xd7, 0xdb, 0x6b, 0x77, 0x47, 0x78, 0x27, 0x51, 0xbe, 0x42, 0x63, 0x0b, 0x35, 0x61, 0xc0,
	0xc2, 0xb3, 0xa3, 0x34, 0xee, 0x02, 0x37, 0x6a, 0x72, 0xb2, 0x72, 0x0a, 0x1b, 0x68, 0x3e, 0x3c,
	0x0b, 0x08, 0xf5, 0x3a, 0xc6, 0x9c, 0xa5, 0xb5, 0x1a, 0xfe, 0x38, 0xc4, 0x87, 0x68, 0x45, 0xf0,
	0x80, 0x26, 0x1f, 0x81, 0x73, 0x88, 0xf6, 0x63, 0x96, 0x52, 0x61, 0xd4, 0x33, 0x4c, 0x7b, 0x43,
	0x5d, 0x5f, 0xf5, 0xa8, 0xf8, 0xf9, 0xed, 0x19, 0x52, 0x6c, 0x3c, 0x2a, 0xfc, 0xd9, 0x1a, 0xfb,
	0x8b, 0x8e, 0xf0, 0x29, 0x8d, 0xee, 0x11, 0xcb, 0xeb, 0x48, 0xb1, 0x1a, 0xbe, 0xee, 0x75, 0xca,
	0x93, 0xe8, 0xd3, 0x93, 0xac, 0xa2, 0x39, 0x39, 0xb2, 0x24, 0x5f, 0xf3, 0xf3, 0x00, 0x6f, 0xa1,
	0x86, 0xea, 0xc9, 0x72, 0x66, 0x0d, 0x7f, 0x92, 0xc0, 0x9b, 0x68, 0x81, 0x43, 0x08, 0x64, 0x08,
	0x5c, 0x11, 0x2b, 0x62, 0xbc, 0x8f, 0x9a, 0x1c, 0x22, 0x80, 0xf8, 0x84, 0x9d, 0x03, 0x95, 0x9c,
	0x1e, 0xb1, 0x93, 0x72, 0x0d, 0x6e, 0xa3, 0x66, 0xd8, 0x27, 0x41, 0x9c, 0xeb, 0x6d, 0xcc, 0xcb,
	0xad, 0x58, 0x4a, 0x16, 0x63, 0x96, 0xad, 0xda, 0x4b, 0xb9, 0xc8, 0xfe, 0xa1, 0xa3, 0xc6, 0x29,
	0xed, 0x32, 0x1a, 0x11, 0xda, 0x2b, 0xd3, 0xd7, 0xa6, 0xe9, 0x1f, 0xa3, 0xb5, 0x6e, 0xca, 0x29,
	0x44, 0x1d, 0xe0, 0x64, 0x18, 0x08, 0x32, 0x04, 0xb5, 0x0d, 0xfd, 0x5f, 0xdb, 0x78, 0xa0, 0x10,
	0xbf, 0x41, 0x2b, 0x39, 0x9b, 0x23, 0x99, 0xcd, 0x75, 0xa8, 0x3e, 0x4e, 0x87, 0xd9, 0x4a, 0x6c,
	0x22, 0x94, 0x4a, 0x22, 0x27, 0x5e, 0x0c, 0xca, 0x65, 0xa5, 0x0c, 0x76, 0x0b, 0xfb, 0xce, 0x49,
	0xa1, 0xd6, 0xd5, 0xc4, 0xcb, 0x05, 0xfd, 0x3b, 0xbe, 0x7d, 0x8e, 0x9e, 0xa4, 0x09, 0xf0, 0xfc,
	0x38, 0x57, 0xd0, 0x8b, 0x12, 0xa3, 0x6e, 0x55, 0x5b, 0x0d, 0xff, 0xbe, 0x23, 0xfb, 0x02, 0x2d,
	0xbf, 0xcc, 0x6c, 0x51, 0x74, 0x4c, 0x26, 0xb6, 0xd1, 0xca, 0xb6, 0x79, 0x35, 0x9e, 0x35, 0xc3,
	0x18, 0xba, 0x55, 0x6d, 0x35, 0x77, 0x6d, 0xe7, 0x81, 0x77, 0xc3, 0x29, 0xda, 0x29, 0xf2, 0xa5,
	0x5a, 0xfb, 0xbb, 0x86, 0x16, 0xbc, 0xf6, 0xc1, 0x71, 0x0a, 0x7c, 0x94, 0xb9, 0xf1, 0x22, 0xfb,
	0x38, 0x19, 0x0d, 0x40, 0x2d, 0x70, 0x92, 0xc0, 0x36, 0x5a, 0x94, 0xc1, 0xdb, 0x40, 0x9c, 0xbd,
	0x86, 0x91, 0x32, 0xf8, 0x54, 0x2e, 0x33, 0x80, 0x20, 0x31, 0xb0, 0x54, 0x28, 0x9f, 0x8f, 0xc3,
	0xb2, 0x35, 0x6a, 0xd3, 0xd6, 0xb0, 0xd1, 0x62, 0xc8, 0x28, 0x85, 0x30, 0x73, 0x5a, 0xf1, 0x0b,
	0x4f, 0xe5, 0x26, 0x32, 0xd4, 0x4b, 0x32, 0xb4, 0xf7, 0x2e, 0x6f, 0x4c, 0xed, 0xea, 0xc6, 0xd4,
	0xfe, 0xdc, 0x98, 0xda, 0xe7, 0x5b, 0xb3, 0x72, 0x75, 0x6b, 0x56, 0x7e, 0xdd, 0x9a, 0x95, 0xf7,
	0x5b, 0xc5, 0x43, 0xfb, 0x69, 0xea, 0xa9, 0x15, 0xa3, 0x01, 0x24, 0xdd, 0xba, 0x7c, 0xfe, 0x5e,
	0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xf4, 0x1a, 0xe4, 0x8f, 0x05, 0x00, 0x00,
}

func (m *DelegationRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegationRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegationRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TransferredAmount.Size()
		i -= size
		if _, err := m.TransferredAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintStake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintStake(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0x2a
	}
	if m.EpochNumber != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.EpochNumber))
		i--
		dAtA[i] = 0x20
	}
	if m.Status != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.DelegationCoin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Id != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *UndelegationRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UndelegationRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UndelegationRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CliamStatus != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.CliamStatus))
		i--
		dAtA[i] = 0x38
	}
	{
		size, err := m.RedeemToken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintStake(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Delegator) > 0 {
		i -= len(m.Delegator)
		copy(dAtA[i:], m.Delegator)
		i = encodeVarintStake(dAtA, i, uint64(len(m.Delegator)))
		i--
		dAtA[i] = 0x22
	}
	if m.Epoch != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintStake(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintStake(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Unbonding) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Unbonding) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Unbonding) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UserUnbondRecordIds) > 0 {
		for iNdEx := len(m.UserUnbondRecordIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.UserUnbondRecordIds[iNdEx])
			copy(dAtA[i:], m.UserUnbondRecordIds[iNdEx])
			i = encodeVarintStake(dAtA, i, uint64(len(m.UserUnbondRecordIds[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.Status != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if m.UnbondTIme != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.UnbondTIme))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.RedeemNativeToken.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.BurnedDerivativeAmount.Size()
		i -= size
		if _, err := m.BurnedDerivativeAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintStake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintStake(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EpochUnbondings) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochUnbondings) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochUnbondings) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Unbondings) > 0 {
		for iNdEx := len(m.Unbondings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Unbondings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStake(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Epoch != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *IBCQuery) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IBCQuery) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IBCQuery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Epoch != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ConnectionID) > 0 {
		i -= len(m.ConnectionID)
		copy(dAtA[i:], m.ConnectionID)
		i = encodeVarintStake(dAtA, i, uint64(len(m.ConnectionID)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintStake(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0x22
	}
	if m.Timeout != 0 {
		i = encodeVarintStake(dAtA, i, uint64(m.Timeout))
		i--
		dAtA[i] = 0x18
	}
	if len(m.QueryPathKey) > 0 {
		i -= len(m.QueryPathKey)
		copy(dAtA[i:], m.QueryPathKey)
		i = encodeVarintStake(dAtA, i, uint64(len(m.QueryPathKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.QueryType) > 0 {
		i -= len(m.QueryType)
		copy(dAtA[i:], m.QueryType)
		i = encodeVarintStake(dAtA, i, uint64(len(m.QueryType)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStake(dAtA []byte, offset int, v uint64) int {
	offset -= sovStake(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DelegationRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovStake(uint64(m.Id))
	}
	l = m.DelegationCoin.Size()
	n += 1 + l + sovStake(uint64(l))
	if m.Status != 0 {
		n += 1 + sovStake(uint64(m.Status))
	}
	if m.EpochNumber != 0 {
		n += 1 + sovStake(uint64(m.EpochNumber))
	}
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovStake(uint64(l))
	}
	l = m.TransferredAmount.Size()
	n += 1 + l + sovStake(uint64(l))
	return n
}

func (m *UndelegationRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovStake(uint64(l))
	}
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovStake(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovStake(uint64(m.Epoch))
	}
	l = len(m.Delegator)
	if l > 0 {
		n += 1 + l + sovStake(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovStake(uint64(l))
	}
	l = m.RedeemToken.Size()
	n += 1 + l + sovStake(uint64(l))
	if m.CliamStatus != 0 {
		n += 1 + sovStake(uint64(m.CliamStatus))
	}
	return n
}

func (m *Unbonding) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovStake(uint64(l))
	}
	l = m.BurnedDerivativeAmount.Size()
	n += 1 + l + sovStake(uint64(l))
	l = m.RedeemNativeToken.Size()
	n += 1 + l + sovStake(uint64(l))
	if m.UnbondTIme != 0 {
		n += 1 + sovStake(uint64(m.UnbondTIme))
	}
	if m.Status != 0 {
		n += 1 + sovStake(uint64(m.Status))
	}
	if len(m.UserUnbondRecordIds) > 0 {
		for _, s := range m.UserUnbondRecordIds {
			l = len(s)
			n += 1 + l + sovStake(uint64(l))
		}
	}
	return n
}

func (m *EpochUnbondings) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovStake(uint64(m.Epoch))
	}
	if len(m.Unbondings) > 0 {
		for _, e := range m.Unbondings {
			l = e.Size()
			n += 1 + l + sovStake(uint64(l))
		}
	}
	return n
}

func (m *IBCQuery) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.QueryType)
	if l > 0 {
		n += 1 + l + sovStake(uint64(l))
	}
	l = len(m.QueryPathKey)
	if l > 0 {
		n += 1 + l + sovStake(uint64(l))
	}
	if m.Timeout != 0 {
		n += 1 + sovStake(uint64(m.Timeout))
	}
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovStake(uint64(l))
	}
	l = len(m.ConnectionID)
	if l > 0 {
		n += 1 + l + sovStake(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovStake(uint64(m.Epoch))
	}
	return n
}

func sovStake(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStake(x uint64) (n int) {
	return sovStake(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DelegationRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegationRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegationRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationCoin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DelegationCoin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= DelegationRecordStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochNumber", wireType)
			}
			m.EpochNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferredAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TransferredAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UndelegationRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UndelegationRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UndelegationRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedeemToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RedeemToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CliamStatus", wireType)
			}
			m.CliamStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CliamStatus |= UndelegationRecordStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Unbonding) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Unbonding: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Unbonding: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnedDerivativeAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BurnedDerivativeAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedeemNativeToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RedeemNativeToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondTIme", wireType)
			}
			m.UnbondTIme = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondTIme |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= UnbondingStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserUnbondRecordIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserUnbondRecordIds = append(m.UserUnbondRecordIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochUnbondings) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochUnbondings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochUnbondings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unbondings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Unbondings = append(m.Unbondings, Unbonding{})
			if err := m.Unbondings[len(m.Unbondings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IBCQuery) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IBCQuery: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IBCQuery: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueryType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryPathKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueryPathKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timeout", wireType)
			}
			m.Timeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timeout |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStake(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStake
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStake
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStake
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStake
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStake
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStake
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStake        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStake          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStake = fmt.Errorf("proto: unexpected end of group")
)
